elems:
  - src: elems/(rbenv-default-gems)$
    dst: ~/.<1>
    only:
      features:
        - rbenv
    notes: This default rbenv gems will be used only if the extension 'rbenv-default-gems' is installed

  - src: elems/(irbrc)$
    dst: ~/.<1>
    only:
      features:
        - ruby
    notes: |
      The following features will be enabled if their requirements are met:
        irb extensions    -> gem 'irbtools' & 'irbtools-more'
        clipboard support -> xclip
